- name: Install Brave Browser
  hosts: all

  tasks:
  # One way to avoid apt_key once it is removed from your distro, armored keys should use .asc extension, binary should use .gpg
  - name: Add brave channel
    block:
    - name: Brave repo
      ansible.builtin.get_url:
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
      become: true

    - name: Apt source
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"
        state: present
      become: true

  - name: Install Brave
    ansible.builtin.apt:
      pkg:
      - brave-browser
      update_cache: true
    become: true
