- name: GitHub Cli install
  hosts: all

  tasks:
    - name: "Install github3 package"
      ansible.builtin.pip:
        name: github3.py
        break_system_packages: true

    - name: "Get Latest Release from Github"
      community.general.github_release:
        user: kubernetes-sigs
        repo: cluster-api
        action: latest_release
      register: release

    - name: Print Latest release
      ansible.builtin.debug:
        var: release

    - name: Download Binary
      ansible.builtin.get_url:
        url: https://github.com/kubernetes-sigs/cluster-api/releases/download/{{ release.tag }}/clusterctl-linux-amd64
        dest: /tmp/clusterctl

    - name: Install Binary
      ansible.builtin.copy:
        src: /tmp/clusterctl
        dest: "/usr/local/bin"
        mode: a+x
        remote_src: true
      become: true
