- name: Install ffmpeg from source
  hosts: all

  tasks:
    - name: Remove apt package
      ansible.builtin.apt:
        pkg:
        - ffmpeg
        state: absent
      become: true

    - name: Install nasm
      ansible.builtin.apt:
        pkg:
        - nasm
        - pkg-config
        - libavcodec-extra58
        - libfdk-aac-dev 
        - libass-dev 
        - libopus-dev
        - libtheora-dev 
        - libvorbis-dev 
        - libvpx-dev 
        - libssl-dev
        - libmp3lame-dev
        - libavdevice-dev
        update_cache: yes
      become: true

    - name: Clone x264
      ansible.builtin.git:
        repo: https://code.videolan.org/videolan/x264.git
        dest: /tmp/x264

    - name: Configure x264
      shell: |
        cd /tmp/x264 && ./configure --enable-static --enable-shared
      become: true

    - name: Compile x264
      shell: |
        cd /tmp/x264 && make -j $(nproc)
      become: true

    - name: Install x264
      shell: |
        cd /tmp/x264 && make install
      become: true

    - name: Clone ffmpeg
      ansible.builtin.git:
        repo: https://git.ffmpeg.org/ffmpeg.git
        dest: /tmp/ffmpeg

    - name: Configure ffmpeg
      shell: |
        cd /tmp/ffmpeg && ./configure --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-nonfree --enable-shared --enable-openssl   
      become: true

    - name: Compile ffmpeg
      shell: |
        cd /tmp/ffmpeg && make -j $(nproc)
      become: true

    - name: Install ffmpeg
      shell: |
        cd /tmp/ffmpeg && make install
      become: true

