- name: Install ffmpeg from source
  hosts: all

  tasks:
    - name: Remove apt package
      ansible.builtin.apt:
        pkg:
        - ffmpeg
        state: absent
      become: true

    - name: Install nasm
      ansible.builtin.apt:
        pkg:
        - nasm
        - pkg-config
        update_cache: yes
      become: true

    - name: Clone ffmpeg
      ansible.builtin.git:
        repo: https://git.ffmpeg.org/ffmpeg.git
        dest: /tmp/ffmpeg

    - name: Configure ffmpeg
      shell: |
        cd /tmp/ffmpeg && ./configure
      become: true

    - name: Compile ffmpeg
      shell: |
        cd /tmp/ffmpeg && make
      become: true

    - name: Install ffmpeg
      shell: |
        cd /tmp/ffmpeg && make install
      become: true
