- name: Install kitten
  hosts: all

  tasks:
    - name: "Install github3 package"
      ansible.builtin.pip:
        name: github3.py

    - name: "Get Latest Release from Github"
      community.general.github_release:
        user: kovidgoyal
        repo: kitty
        action: latest_release
      register: release

    - name: Print Latest release
      ansible.builtin.debug:
        var: release

    - name: Download Binary
      ansible.builtin.get_url:
        url: https://github.com/kovidgoyal/kitty/releases/download/{{ release.tag }}/kitten-linux-amd64
        dest: /tmp/kitten

    - name: Install Binary
      ansible.builtin.copy:
        src: /tmp/kitten
        dest: /home/{{ ansible_user_id }}/.local/bin/
        remote_src: true
        mode: a+x

