- name: GitHub Cli install
  hosts: all

  tasks:
    - name: "Install github3 package"
      ansible.builtin.pip:
        name: github3.py
        break_system_packages: true

    - name: "Get Latest Release from Github"
      community.general.github_release:
        user: neovide
        repo: neovide
        action: latest_release
      register: release

    - name: Print Latest release
      ansible.builtin.debug:
        var: release

    - name: Create $HOME/Programs/neovide directory
      ansible.builtin.file:
        path: /home/{{ ansible_user_id }}/Programs/neovide
        state: directory
        mode: '0755'

    - name: Download Binary
      ansible.builtin.unarchive:
        src: https://github.com/neovide/neovide/releases/download/{{ release.tag }}/neovide-linux-x86_64.tar.gz
        dest: /home/{{ ansible_user_id }}/Programs/neovide
        remote_src: true

    - name: Chmod binary
      ansible.builtin.file:
        path: /home/{{ ansible_user_id }}/Programs/neovide/neovide
        mode: '0777'

    - name: Install Binary
      ansible.builtin.file:
        src: /home/{{ ansible_user_id }}/Programs/neovide/neovide
        dest: "/usr/local/bin/neovide"
        state: link
      become: true
