- name: GitHub Cli install
  hosts: all

  tasks:
  - name: Add nextcloud-devs ppa
    block:
    - name: Apt source
      ansible.builtin.apt_repository:
        repo: ppa:nextcloud-devs/client
        state: present
      become: true

  - name: Install Nextcloud-client
    ansible.builtin.apt:
      pkg:
      - nextcloud-client
      update_cache: true
    become: true
