- name: Install waybar
  hosts: all

  tasks:
  - name: Install packages
    ansible.builtin.apt:
      pkg:
      - "{{ item }}"
      update_cache: true
    loop:
      - meson
      - cairo
      - libxkbcommon-dev
      - scdoc
    become: true
    ignore_errors: true

  - name: Clone repo
    ansible.builtin.git:
      repo: https://github.com/emersion/slurp
      dest: /tmp/slurp

  - name: Configure
    shell: |
      cd /tmp/slurp && meson setup build && ninja -C build install
    become: true
