- name: GitHub Cli install
  hosts: all

  tasks:
    - name: Install tmux from apt
      apt:
        pkg:
        - tmux
        update_cache: yes
      become: true
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '24.04'

    - name: Exit the playbook early
      meta: end_play
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '24.04'

    - name: "Install github3 package"
      ansible.builtin.pip:
        name: github3.py
        break_system_packages: true

    - name: Install openssl
      ansible.builtin.apt:
        pkg:
        - libssl-dev
      become: true

    - name: Get Latest libevent Release from Github"
      community.general.github_release:
        user: libevent
        repo: libevent
        action: latest_release
      register: release

    - name: Print Latest release
      ansible.builtin.debug:
        var: release

    - name: Download libevent
      ansible.builtin.unarchive:
        src: https://github.com/libevent/libevent/releases/download/{{ release.tag }}/{{ release.tag | replace("release", "libevent") }}.tar.gz
        dest: /tmp
        remote_src: true

    - name: Configure libevent
      shell: |
        cd /tmp/{{ release.tag | replace("release", "libevent") }} && ./configure && make

    - name: Install libevent
      shell: |
        cd /tmp/{{ release.tag | replace("release", "libevent") }} && make install
      become: true

    - name: Download ncurses
      ansible.builtin.unarchive:
        src: https://invisible-mirror.net/archives/ncurses/ncurses-6.4.tar.gz
        dest: /tmp
        remote_src: true

    - name: Configure ncurses
      shell: |
        cd /tmp/ncurses-6.4 && ./configure

    - name: Install ncurses
      shell: |
        cd /tmp/ncurses-6.4 && make install
      become: true

    - name: Get Latest tmux Release from Github"
      community.general.github_release:
        user: tmux
        repo: tmux
        action: latest_release
      register: release

    - name: Download tmux
      ansible.builtin.unarchive:
        src: https://github.com/tmux/tmux/releases/download/{{ release.tag }}/tmux-{{ release.tag }}.tar.gz
        dest: /tmp
        remote_src: true

    - name: Configure tmux
      shell: |
        cd /tmp/tmux-{{ release.tag }} && ./configure && make

    - name: Install libevent
      shell: |
        cd /tmp/tmux-{{ release.tag }} && make install
      become: true

    - name: Create tmux conf
      ansible.builtin.file:
        src: "{{ playbook_dir }}/../../tmux/tmux.conf"
        dest: /home/{{ ansible_user_id}}/.tmux.conf
        state: link

    - name: Create .tmux dir
      ansible.builtin.file:
        path: /home/{{ ansible_user_id}}/.tmux/plugins
        state: directory

    - name: Create themes dir
      ansible.builtin.file:
        src: "{{ playbook_dir }}/../../tmux/themes"
        dest: /home/{{ ansible_user_id}}/.tmux/themes
        state: link

    - name: Clone tpm
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm
        dest: /home/{{ ansible_user_id}}/.tmux/plugins/tpm

    - name: Run tpm install
      shell: /home/{{ ansible_user_id}}/.tmux/plugins/tpm/scripts/install_plugins.sh
