- name: Ueberzugpp Install
  hosts: all

  tasks:
    - name: Download deb package
      ansible.builtin.get_url:
        url: https://download.opensuse.org/repositories/home:/justkidding/xUbuntu_22.04/amd64/ueberzugpp_2.9.2_amd64.deb
        dest: /tmp/ueberzugpp.deb

    - name: Install Binary
      delegate_to: app1
      apt:
        deb: /tmp/ueberzugpp.deb
      become: true
