- name: Install waybar
  hosts: all

  tasks:
  - name: Install packages
    ansible.builtin.apt:
      pkg:
      - "{{ item }}"
      update_cache: true
    loop:
      - clang-tidy
      - gobject-introspection
      - libdbusmenu-gtk3-dev
      - libevdev-dev
      - libfmt-dev
      - libgirepository1.0-dev
      - libgtk-3-dev
      - libgtkmm-3.0-dev
      - libinput-dev
      - libjsoncpp-dev
      - libmpdclient-dev
      - libnl-3-dev
      - libnl-genl-3-dev
      - libpulse-dev
      - libsigc++-2.0-dev
      - libspdlog-dev
      - libwayland-dev
      - meson
      - scdoc
      - upower
      - libxkbregistry-dev
    become: true
    ignore_errors: true

  - name: Clone repo
    ansible.builtin.git:
      repo: https://github.com/Alexays/Waybar
      dest: /tmp/waybar

  - name: Configure
    shell: |
      cd /tmp/waybar && meson setup build && ninja -C build install
    become: true
