- name: Install yamlfmt
  hosts: all

  tasks:
    - name: Install binary
      shell: |
        go install github.com/google/yamlfmt/cmd/yamlfmt@latest

    - name: Create config directories
      ansible.builtin.file:
        path: /home/{{ ansible_user_id }}/.config/yamlfmt
        state: directory
        mode: '0755'

    - name: Install config
      ansible.builtin.copy:
      src: ../../../config/yamlfmt/yamlfmt
      dest: /home/{{ ansible_user_id }}/.config/yamlfmt/.yamlfmt
