---
- name: install packages
  hosts: localhost
  become: true
  tasks:
  - name: Install localhost
    ansible.builtin.apt:
      pkg: 
        - software-properties-common
        - mysql-server
        - php8.1 # Change 8.1 to whatever newest version is
        - php8.1-mysql
        - php8.1-curl
        - php8.1-gd
        - php8.1-mbstring
        - php8.1-dom 
        - php8.1-xmlwriter
        - php8.1-zip
      update_cache: yes
      cache_valid_time: 3600

    - name: Configure mysql
      expect:
        command: mysql_secure_installation
        responses:
          'Enter current password for root': ''
          'Set root password': 'n'
          'Remove anonymous users': 'y'
          'Disallow root login remotely': 'y'
          'Remove test database': 'y'
          'Reload privilege tables now': 'y'
        timeout: 1
      register: secure_mariadb
      failed_when: "'... Failed!' in secure_mariadb.stdout_lines"

    - name: Create a new database with name 'nextcloud'
      community.mysql.mysql_db:
        name: nextcloud
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock

    - name: Create database user with name 'nextcloud' and password '12345' with all database privileges
      community.mysql.mysql_user:
        name: nextcloud
        password: 12345
        priv: '*.*:ALL'
        state: present

