---
- name: instlocalhost packages
  hosts: localhost
  tasks:
  - name: Install localhost
    become: yes
    become_user: root
    ansible.builtin.apt:
      pkg: 
      - zsh 
      - git
      - fzf
      - silversearcher-ag
      update_cache: yes
      cache_valid_time: 3600

- name: Change default sh
   become_user: root
   ansible.builtin.command: chsh -s /usr/bin/zsh root && chsh -s /usr/bin/zsh huy

- name: Install and configure nvim
  hosts: localhost

  tasks:
  - name: Check if nvim exists
    ansible.builtin.command: which nvim
    register: nvim_exists
    ignore_errors: true

  - name: Download nvim
    ansible.builtin.get_url:
      url: https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz
      dest: /tmp/nvim.tar.gz
      mode: '0440'
    when: nvim_exists is failed

  - name: Make dir
    ansible.builtin.command: mkdir -p /home/huy/Programs/nvim
    when: nvim_exists is failed

  - name: Extract nvim
    ansible.builtin.command: tar xzvf /tmp/nvim.tar.gz -C /home/huy/Programs/nvim
    when: nvim_exists is failed

  - name: Chmod
    ansible.builtin.command: chmod +x /home/huy/Programs/nvim/nvim-linux64/bin/nvim
    when: nvim_exists is failed

  - name: Add nvim to PATH
    ansible.builtin.command: ln -s /home/huy/Programs/nvim/nvim-linux64/bin/nvim /home/huy/.local/bin
    when: nvim_exists is failed

  - name: Make .config dir
    ansible.builtin.command: mkdir -p /home/huy/.config

  - name: Create nvim config dir
    ansible.builtin.command: ln -s $PWD/../nvim /home/huy/.config/
# 
 - name: Install oh-my-zsh
   hosts: localhost
   become: yes
# 
  tasks:
  - name: Check if .oh-my-zsh exists
    ansible.builtin.command: ls /home/huy/.oh-my-zsh
    register: omz_exists

  - name: Download oh-my-zsh installation
    ansible.builtin.get_url:
      url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      dest: /tmp/install.sh
      mode: '0700'
    when: omz_exists is failed

  - name: oh-my-zsh installation
    ansible.builtin.command: sh -c /tmp/install.sh
    when: omz_exists is failed

  - name: Install oh-my-zsh config
    ansible.builtin.command: rm -f /home/huy/.zshrc && ln -s $PWD/../zsh/.zshrc /home/huy/.zshrc

  - name: Install zsh aliases
    ansible.builtin.command: ln -s $PWD/zsh/.zsh_aliases /home/huy/.oh-my-zsh/.zsh_aliases

  - name: Install zsh aliases
    ansible.builtin.command: ln -s $PWD/zsh/.zsh_vi.zsh /home/huy/.oh-my-zsh/.zsh_vi.zsh

  - name: Install oh-my-zsh custom-zsh-syntax-highlighting
    ansible.builtin.git:
      repo: https://github.com/zsh-users/zsh-syntax-highlighting
      dest: /home/huy/.oh-my-zsh/plugins/zsh-syntax-highlighting
    ignore_errors: true

  - name: Install oh-my-zsh custom-powerlevel10k
    ansible.builtin.git:
      repo: https://github.com/romkatv/powerlevel10k.git
      dest: /home/huy/.oh-my-zsh/themes/zsh-syntax-highlighting
    ignore_errors: true
# 
