- name: Install new Ubuntu work machine
  hosts: all

  tasks:
  - name: Install packages
    ansible.builtin.apt:
      pkg:
      - ansible-core
      - libfuse-dev
      - libreoffice
      - git
      update_cache: true
    become: true

  - name: Create Programs directory
    ansible.builtin.file:
      path: /home/{{ ansible_user_id }}/Programs
      state: directory

- import_playbook: installers/brave-browser.yaml
- import_playbook: installers/chrome.yaml
- import_playbook: installers/clusterctl.yaml
- import_playbook: installers/doomemacs.yaml
- import_playbook: installers/drawio.yaml
- import_playbook: installers/dropbox.yaml
- import_playbook: installers/ffmpeg.yaml
- import_playbook: installers/firefox.yaml
- import_playbook: installers/gh.yaml
- import_playbook: installers/greenclip.yaml
- import_playbook: installers/i3blocks.yaml
- import_playbook: installers/image.nvim.yaml
- import_playbook: installers/kitty.yaml
- import_playbook: installers/minikube.yaml
- import_playbook: installers/neovide.yaml
- import_playbook: installers/nextcloud-client.yaml
- import_playbook: installers/nvim.yaml
- import_playbook: installers/nvm.yaml
- import_playbook: installers/oh-my-bash.yaml
- import_playbook: installers/playerctl.yaml
- import_playbook: installers/tmux.yaml
- import_playbook: installers/tree_sitter.yaml
- import_playbook: installers/vscodium.yaml
- import_playbook: installers/yamlfmt.yaml
- import_playbook: installers/yq.yaml
