- name: Install new Ubuntu work machine
  hosts: all

  tasks:
  - name: Install packages
    ansible.builtin.apt:
      pkg:
      - "{{ item }}"
      update_cache: true
    loop:
      - libfuse-dev
      - libreoffice
      - git
      - curl
      - python3-pip
      - fzf
      - silversearcher-ag
      - python3-venv
      - pipx
      - libc6-dev
      - jq
      - ripgrep
      - qemu
      - qemu-kvm
      - libvirt-dev
      - libvirt-clients
      - libvirt-daemon-system
      - virtinst
      - bridge-utils
      - ranger
      - pkg-config
      - zsh
    become: true
    ignore_errors: true

  - name: Create Programs directory
    ansible.builtin.file:
      path: /home/{{ ansible_user_id }}/Programs
      state: directory

- import_playbook: installers/brave-browser.yaml
  ignore_errors: true
- import_playbook: installers/chrome.yaml
  ignore_errors: true
- import_playbook: installers/clusterctl.yaml
  ignore_errors: true
- import_playbook: installers/drawio.yaml
  ignore_errors: true
- import_playbook: installers/dropbox.yaml
  ignore_errors: true
- import_playbook: installers/ffmpeg.yaml
  ignore_errors: true
- import_playbook: installers/firefox.yaml
  ignore_errors: true
- import_playbook: installers/gh.yaml
  ignore_errors: true
- import_playbook: installers/greenclip.yaml
  ignore_errors: true
- import_playbook: installers/i3blocks.yaml
  ignore_errors: true
- import_playbook: installers/image.nvim.yaml
  ignore_errors: true
- import_playbook: installers/kitty.yaml
  ignore_errors: true
- import_playbook: installers/minikube.yaml
  ignore_errors: true
- import_playbook: installers/neovide.yaml
  ignore_errors: true
- import_playbook: installers/nextcloud-client.yaml
  ignore_errors: true
- import_playbook: installers/nvim.yaml
  ignore_errors: true
- import_playbook: installers/nvm.yaml
  ignore_errors: true
- import_playbook: installers/oh-my-bash.yaml
  ignore_errors: true
- import_playbook: installers/playerctl.yaml
  ignore_errors: true
- import_playbook: installers/tmux.yaml
  ignore_errors: true
- import_playbook: installers/tree_sitter.yaml
  ignore_errors: true
- import_playbook: installers/vscodium.yaml
  ignore_errors: true
- import_playbook: installers/yamlfmt.yaml
  ignore_errors: true
- import_playbook: installers/yq.yaml
  ignore_errors: true
